# Generated by Django 6.1.1 on 2026-09-12 13:23

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inmuebles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inmueble',
            name='fecha_ultima_modificacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha Última Modificación'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='comuna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_inmuebles.comuna', verbose_name='Comuna'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='estacionamientos',
            field=models.PositiveIntegerField(verbose_name='Número de Estacionamientos'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='habitaciones',
            field=models.PositiveIntegerField(verbose_name='Cantidad de Habitaciones'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='precio_mensual',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio Mensual'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='tipo_inmueble',
            field=models.CharField(choices=[('Casa', 'Casa'), ('Departamento', 'Departamento'), ('Parcela', 'Parcela')], max_length=50, verbose_name='Tipo de Inmueble'),
        ),
    ]
