# Generated by Django 6.1.1 on 2026-09-16 00:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inmuebles', '0003_tipoinmueble_alter_usuario_tipo_usuario_por_defecto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='precio_mensual',
            field=models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio Mensual'),
        ),
    ]
